### ISSUE TITLE
cmake . fails on MacOS (Ventura 13.5)

### ISSUE THREAD

**Issue by gasparschott** [ScanTailor-Advanced/scantailor-libs-build#14]
CMake Error at core/CMakeLists.txt:140 (translation_sources):
  Unknown CMake command "translation_sources".

**Comment by ghost** [comment]
Hello @gasparschott 

The build instructions are designed for Windows or Linux only, building for macOS is still not integrated into the guide, see issue #3 for more details.

**Comment by ghost** [comment]
Duplicate of #3

**Comment by mara004** [comment]
(formerly) @lightsilverberryfox did you just delete your account or something?
