### ISSUE TITLE
Cmake 3.22 no longer accepts the --build option (in favour of -B)

### ISSUE THREAD

**Issue by Fifis** [ScanTailor-Advanced/scantailor-libs-build#6]
Good afternoon! On Linux Mint 21.1 (based on Ubuntu 22.04 LTS), the current version of CMake is 3.22, which changes the building instructions slightly:

```
mkdir build
cmake -G "Unix Makefiles" -B build/
cd build/
make -j<YOUR # OF CORES>
cpack -G "DEB"
sudo dpkg -i scantailor-advanced-1.0.18-Linux.deb
```

The old instruction produces this error:
```
cmake -G "Unix Makefiles" --build ..
CMake Error: Unknown argument --build
CMake Error: Run 'cmake --help' for all supported options.
```

It would be wise to create a separate alternative instruction for those systems where `cmake` does not support the `build` argument.

**Comment by lockywolf** [comment]
Both of those are wrong.

You need to (1) configure:
```
mkdir build
cd build 
cmake ..
```
then (2) build:
```
cmake --build .
```
The dots after `-build` must point to the already configured directory.

**Comment by owenh000** [comment]
@lightsilverberryfox, please merge #11 which fixes this issue.

(I'm not sure why I have to fight the GitHub interface to open a pull request for this repository rather than the parent 4lex4 one.)
