### ISSUE TITLE
Don't recommend building Qt and Boost from scratch on Linux.

### ISSUE THREAD

**Issue by lockywolf** [ScanTailor-Advanced/scantailor-libs-build#8]
That's a crazy idea, just use your repo's libraries. Even if you shall need to build those libs yourself, "the margins of this book are too narrow" to include the build instructions.

**Comment by lightsilverberryfox** [comment]
Sorry for the long time to answer. I do agree, in fact, I discussed this with Vigri on issue #4

**Comment by mara004** [comment]
No, please don't do this, see https://github.com/ScanTailor-Advanced/scantailor-libs-build/pull/13#issuecomment-1677948228.

> "the margins of this book are too narrow" to include the build instructions.

I am in doubt, it is valuable to have at least some directive how to build the dependencies in this place, I think.

**Comment by mara004** [comment]
> I discussed this with @vigri on issue https://github.com/ScanTailor-Advanced/scantailor-libs-build/issues/4

But didn't @vigri say "I would actually leave the information in. It is optional, after all." ? (Source: https://github.com/ScanTailor-Advanced/scantailor-libs-build/issues/4#issuecomment-1481937179)
